basic_trainer:
  active: True
  val_path: "resources/images/calibrated_masked/not-cropped/ycb_video/val_dataset.json"
  train_path: "resources/images/calibrated_masked/not-cropped/ycb_video/train_dataset.json"

oof_trainer:
  active: False
  dataset_path: ""
  oof_p: 0.33

network_config:
  initial_channels: 64
  epochs: 50
  batch_size: 4
  learning_rate: 0.05
  lr_patience: 10
  load_from_model: None
  wandb: True
  save: True
  evaluation_dir: local_resources/models
  bilinear: True
  amp: False
  validation_interval: 250
  optimizer_name: 'rmsprop'

dataset_config:
  scale_images: 1
  add_nan_mask_to_input: True
  add_region_mask_to_input: True
  normalize_depths: 
    active: False # normalized input and label depth d with (d - mean) / std channel wise
    min: 0
    max: 0


