basic_trainer:
  active: True
  val_path: "resources/images/calibrated_masked_augmented/cropped/ycb_video/val_dataset.json"
  train_path: "resources/images/calibrated_masked_augmented/cropped/ycb_video/train_dataset.json"

oof_trainer:
  active: False
  dataset_path: ""
  oof_p: 0.33

network_config:
  epochs: 50
  batch_size: 1
  learning_rate: 0.1
  load_from_model: None
  wandb: True
  save: True
  evaluation_dir: "resources/models"
  bilinear: True
  amp: False
  validation_interval: 300

dataset_config:
  scale_images: 0.5
  enable_augmentation: False
  add_nan_mask_to_input: True
  add_region_mask_to_input: True
  normalize_depths: True # normalized input and label depth d with (d - mean) / std channel wise
