basic_trainer:
  active: True
  val_path: "resources/images/calibrated_masked/not-cropped/ycb_video/val_dataset.json"
  train_path: "resources/images/calibrated_masked/not-cropped/ycb_video/train_dataset.json"

oof_trainer:
  active: False
  dataset_path: ""
  oof_p: 0.33

network_config:
  initial_channels: 8
  epochs: 50
  batch_size: 35
  learning_rate: 0.1
  lr_patience: 2
  load_from_model: None
  wandb: True
  save: True
  evaluation_dir: local_resources/hp_models
  bilinear: False
  amp: False
  validation_interval: 250
  optimizer_name: rmsprop
  loss_type: huber_loss
  output_activation: none

dataset_config:
  scale_images: 1
  add_nan_mask_to_input: False
  add_region_mask_to_input: False
  normalize_depths: 
    active: False # normalized input and label depth d with (d - mean) / std channel wise
    min: 0
    max: 0
  resize_region_to_fill_input: False
  clean_by_depth_distance: True

